package:
  name: r-dids
  version: 0.9.1
source:
  path: ../
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r
    - 'bioconductor-biobase'
  run:
    - r
    - 'bioconductor-biobase'
test:
  commands:
    - '$R -e "library(''dids'')"'
about:
  home: http://ccb.nki.nl/software/
  license: GPL-3
  summary: "R package for DIDS (Detection of Imbalanced Differential
    Signal). The original version of DIDS was written by Jorma de Ronde
    and is available at http://ccb.nki.nl. For more details about the
    approach please read corresponding the publication 'Identifying
    subgroup markers in heterogeneous populations'
    (http://www.ncbi.nlm.nih.gov/pubmed/24062158)."